apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nagios-ingress
spec:
  rules:
  - host: nagios.hscloud.am
    http:
      paths:
      - backend:
          serviceName: nagios-service
          servicePort: 80