variables:
  LATEST_VER: pogossian/nagios-k8s:latest
  MAJOR_VER: pogossian/nagios-k8s:v1
  MINOR_VER: pogossian/nagios-k8s:v1.4
  deploy_host: 185.92.84.173
  deploy_ssh_port: 44022
  deploy_ssh_username: gorpoghosyan
  deploy_path: ~/

stages:
- Build image
- Push to Docker Hub
- Deploy

build image:
  stage: Build image
  script:
  - docker info
  - docker build -t $LATEST_VER -t $MAJOR_VER -t $MINOR_VER .


push image:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $LATEST_VER && docker image rm $LATEST_VER
  - docker push $MAJOR_VER && docker image rm $MAJOR_VER
  - docker push $MINOR_VER && docker image rm $MINOR_VER


deploy on k8s:
  stage: Deploy
  before_script:
  - ssh $deploy_host -p $deploy_ssh_port -l $deploy_ssh_username "export GIT_SSL_NO_VERIFY=1 && rm -rf ${deploy_path}/${CI_PROJECT_NAME} && git clone $CI_REPOSITORY_URL"
  script:
  - ssh $deploy_host -p $deploy_ssh_port -l $deploy_ssh_username "kubectl apply -f ${deploy_path}/${CI_PROJECT_NAME}/.kube/"